adding council page
uoe-dlam/witches pull request #134
Opened 2024-09-20 10:37 UTC by rubyimrie

adding council page, no big changes

2024-09-30 13:53 UTC, Sephster requested changes
minor comment over the link but otherwise looks good. Thanks Ruby

2024-09-30 13:53 UTC, Sephster commented on components/MainNavBar.vue
> +             { name : 'Trials in Each Modern Authority', url: '/council', external: false },
I think the link should be changed to be `trials-in-each-modern-authority` to match the link text

2024-10-10 12:01 UTC, Sephster requested changes

2024-10-10 12:41 UTC, rubyimrie commented on components/MainNavBar.vue
> +            <<<<<<< HEAD =======
done

2024-10-10 13:45 UTC, Sephster commented on components/MainNavBar.vue
> +            <<<<<<< HEAD =======
Thank you

2024-10-10 13:45 UTC, Sephster approved these changes

2024-10-10 13:46 UTC, merged